# Site settings
title: Pranav's Blog
description: AI, Python, and ML content
author: Pranav K Jha
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pranav-k-jha.github.io" # the base hostname & protocol for your site

# theme: minima  # Commented out to use custom styles
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# Include these directories
include:
  - _pages
  - _sass
  - assets
  - assets/css
  - assets/css/*

# Sass settings
sass:
  style: compressed  # Minify CSS output
  sass_dir: _sass   # Directory containing your sass files
  sourcemap: never  # Disable sourcemaps in development

# Exclude these from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor
#   - .git
#   - .gitignore
#   - README.md
#   - docker-compose.yml
#   - Dockerfile
#   - .dockerignore
#   - Gemfile.lock
#   - node_modules
#   - vendor

# Blog settings
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
