# Development-specific configuration
quiet: true
sass:
  style: compressed
  trace_selectors: true
  debug_info: false
  quiet: true
  sourcemap: never

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - .git
  - .gitignore
